export default {
  SEND_CODE_TO: 'Ellenörzőkód küldése',
  SEND_VERIFICATION: 'Ellenörzőkód küldése',
  ENTER_CODE: 'SMS-ben kapott kód',
  DIDNT_GET: 'Nem kapta meg az sms-t?',
  PASSWORD: 'Jelszó',
  PASSWORD_AGAIN: 'Jelszó újra',
  MODIFY_PASSWORD: 'Jelszó módosítása',
  RESEND: 'Újraküld',
  LOGIN_WITH: 'Bejelentkezés',
  LOGIN: 'Belép',
  NEW_ACCOUNT: 'Új felhasználó',
  FORGOT_PW: 'Elfelejtette jelszavát?',
  REG_WITH: 'Regisztráció',
  I_ACCEPT: 'Elfogadom a ',
  PRIVACY: 'Adatvédelmi nyilatkozatot',
  TERMS: 'Felhasználási feltételeket',
  REGISTRATION: 'Regisztráció',
};
