export default {
  COL_TITLE: 'A bőröm',
  COL_N_ALBUM: 'Új album',
  COL_N_ALBUM_NAME: 'Album neve',
  COL_REMINDER: 'Emlékeztető',
  NOTIF_WEEKLY: 'Hetente',
  NOTIF_MONTHLY: 'Havonta',
  NOTIF_NEVER: 'Soha',
  COL_CREATE: 'Kész',
  COL_CANCEL: 'Mégsem',
  COL_N_PHOTOS: 'Új fotók',
  COL_EDIT: 'Album módosítása',
  COL_ARCHIVE: 'Archivál',
  COL_INFORMATIONS: 'Információk',
  COL_START: 'Kezdéshez készítsen egy új fényképet! ;)',
  COL_TAG: 'Új',
  COL_STATUS_SENT: 'Elküldve',
  COL_STATUS_SEEN: 'Az orvos látta',
  COL_STATUS_INP: 'Folyamatban',
  COL_STATUS_UNSENT: 'Nem elküldött',
  COL_UPDATED: 'Utolsó frissítés: ',
  COL_ALREADY_ARCHIVED: 'Az album már archiválásra került.',
  COL_FIN_SEND: 'Elküld',
  COL_SURE_ARCHIVE_Q: 'Biztosan archiválni szeretnéd az albumot??',
  COL_SURE_ARCHIVE_D: 'Amennyiben archiválja az albumont a tartalmát továbbra is megtekintheti, ugyanakkor a jövőben már nem módosíthatja.',
  COL_YES: 'Igen',
  COL_NO: 'Mégsem',
};
