export default {
  UNREAD: 'Olvasatlan',
  MESSAGES: 'Üzenetek',
  NEW_MESSAGE: 'új üzenet',
  HOME: 'Főoldal',
  MED_STATIONS: 'Időpont foglalása',
  MY_MELANOMAS: 'A bőröm',
  DOCUMENTS: 'Dokumentumok',
  SETTINGS: 'Beállítások',
  HAVENT_UPDATED: 'Nem frissítetted a fényképeidet közel ',
  FIND_DOCTOR: 'Rendelő keresése',
  OPEN_NOW: 'Nyitva',
  PRIVATE: 'Privát',
  NOT_PRIVATE: 'Nem privát',
  APOINTMENT: 'Időpont foglalása',
  YOUR_DOCTOR: 'Practicioners',
  HOSPITAL_TYPE: 'Rendelő típusa',
  PROFILE: 'Profil',
  MY_PRACTICIONERS: 'Orvosaim',
  CONTACTS: 'Elérhetőség',
};
