export default {
  WELCOME: 'Welcome',
  THANKS: 'Thanks for choosing Merwis!',
  BEFORE: 'Before creating an appointment, our doctors need some information.',
  FILL: 'Start survey',
  SURVEY1: 'Survey 1/3',
  SURVEY2: 'Survey 2/3',
  SURVEY3: 'Survey 3/3',
  OUTDOOR: 'Do you spend most of your time outdoors? ',
  SOLARIUM: 'How often do you visit tanning parlours?  ',
  SUN_PROTECT: 'Do you regularly use an SPF30+ suntan lotion/milk in the summertime? ',
  SMOKING: 'Are you a smoker?  ',
  FACTOR: 'Factor',
  ALMOST: 'Almost finished!',
  SLIDER_TUTORIAL: 'Please move the slider to the correct answer',
  SERIOUS: 'In your lifetime, have you got sunburns on more than 5 occasions? ',
  CANCER: 'Has any blood relative had an occurence of skin cancer? ',
  BROWNIE: 'Are you more likely to get a nice suntan or a sunburn? ',
  BLONDIE: 'Are you a blonde or a readahead?',
  COMPLETE: 'Complete 3/3',
  CONGRATS_READY: 'Congratulations, you are ready to use Merwis!',
  CHANGE: 'You can change your data in the \'Profile\' menu',
  LEAVE: 'Are you sure, you want to quit filling your profile?',
  CANT_CREATE_APPOINTMENT: 'You can\'t create new appointments without filling your profile',
  LEAVE_CONFIRM: 'Yes, quit',
  // Unused
  SCHOOL: 'Highest qualification',
  VACATION: 'Tropical vacation count',
  BLUELIGHT: 'Bluelight treatment as newborn',
  MELANOMA: 'Melanom in the family',
  COLORED_BIRTHMARK: 'High count of pigmented birthmarks in teh family',
  HPV: 'HPV infection before',
  IONIZING_RAY: 'Ionizing ray before (dosimetry)',
  CONTAMINATION: 'Asphalt - paraffin - arsenic contamination',
  IMMUN: 'Immunosuppressive medicine usage',
};
